### ISSUE TITLE
Chrome 109 (latest stable) Broke This Extension

### ISSUE THREAD

**Issue by zzzpppzzz** [oslego/chrome-backspace-back#13]
Hello,

I know this looks like it is no longer maintained, but I have been using this extension for years and it has been working well until recently.

It looks like the recent Chrome 109 update (latest stable channel version) has broken the extension.

**Comment by oslego** [comment]
Chrome 109 [deprecated `Event.path`](https://chromestatus.com/feature/5726124632965120) which the extension was using. 
Fixed by using the standard [`Event.composedPath()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath).

**Comment by zzzpppzzz** [comment]
Awesome. Thanks for the quick fix!
