### ISSUE TITLE
Shift-backspace doesn't go forward

### ISSUE THREAD

**Issue by MisterTickle** [oslego/chrome-backspace-back#7]
As well as "back to go back", Chrome use to allow you to navigate FORWARDS in the history when you pressed shift-backspace.
To fully replicate the old behaviour please would you consider also adding that function? I used to use it a lot!

**Comment by oslego** [comment]
Fixed with 089af486cd42ef12300c1a7ed1fd53de34df0559 and pushed update to Chrome Web Store in [version 1.1](https://chrome.google.com/webstore/detail/backspace-to-go-back/nlffgllnjjkheddehpolbanogdeaogbc?hl=en-US&gl=GB)

**Comment by MisterTickle** [comment]
Great, thank you so much! :)
